default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whether_sweater_api_development

test:
  <<: *default
  database: whether_sweater_api_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: whether_sweater_api_production
  username: whether_sweater_api
  password: <%= ENV["WHETHER_SWEATER_API_DATABASE_PASSWORD"] %>
